[package]
name = "behelit"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm-siv = "0.11.*"
rsa = "0.8.*"
lazy_static = "1.4.*"
tokio = {version="1.27.*", features=["full"]}
sled = "0.34.*"
serde = {version="1.0.*", features=["derive"]}